# Generated by Django 3.1.4 on 2021-01-03 12:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('agent', '0002_agent_user'),
        ('user_profile', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransferBalance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(default=0)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(default=0)),
                ('agents_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agent.agent')),
                ('profile_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_profile.profile')),
            ],
        ),
        migrations.CreateModel(
            name='BalanceWithdraw',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('withdraw_type', models.CharField(default='', max_length=200)),
                ('payment_method', models.CharField(default='', max_length=250)),
                ('Marchant_Method', models.CharField(default='', max_length=250)),
                ('transaction_pin', models.CharField(default='', max_length=250)),
                ('transaction_amount', models.IntegerField(default=0)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(default=0)),
                ('agents_user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agent.agent')),
            ],
        ),
        migrations.CreateModel(
            name='BalanceExchange',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(default=0)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(default=0)),
                ('receiver_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agent.agent')),
                ('sender_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_profile.profile')),
            ],
        ),
        migrations.CreateModel(
            name='Balance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_id', models.CharField(max_length=250, unique=True)),
                ('btc_address', models.TextField(blank=True, max_length=300, null=True)),
                ('agent_transaction_id', models.CharField(max_length=250, unique=True)),
                ('sending_amount', models.IntegerField(default=0)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(default=0)),
                ('agent_user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agent.agent')),
            ],
        ),
    ]
