# Generated by Django 3.1.5 on 2021-01-16 17:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(blank=True, max_length=200, null=True)),
                ('address', models.TextField(blank=True, max_length=300, null=True)),
                ('country', models.CharField(blank=True, max_length=200, null=True)),
                ('photo', models.ImageField(upload_to='agent_photos/%Y/%m/%d')),
                ('mobile_no', models.CharField(blank=True, max_length=200, null=True)),
                ('tnx_no', models.IntegerField(default=0)),
                ('division', models.CharField(blank=True, max_length=200, null=True)),
                ('district', models.CharField(blank=True, max_length=200, null=True)),
                ('thana', models.CharField(blank=True, max_length=200, null=True)),
                ('BTCAddress', models.CharField(default='', max_length=200, unique=True)),
                ('transaction_id', models.IntegerField(default=0)),
                ('status', models.BooleanField(default=True)),
                ('birth_date', models.DateTimeField(default=0)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
