# Generated by Django 3.1.4 on 2021-01-03 11:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('agent', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('package_name', models.CharField(default='primary', max_length=200)),
                ('package_amount', models.FloatField(default=0)),
                ('duration', models.TimeField(default=0)),
                ('description', models.TextField(blank=True, max_length=300, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UsePositionStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('status_id', models.CharField(max_length=250, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=250, unique=True)),
                ('full_name', models.CharField(blank=True, max_length=200, null=True)),
                ('address', models.TextField(blank=True, max_length=300, null=True)),
                ('country', models.CharField(blank=True, max_length=200, null=True)),
                ('photo', models.ImageField(upload_to='photos/%Y/%m/%d')),
                ('mobile_no', models.CharField(blank=True, max_length=20, null=True)),
                ('tnx_no', models.IntegerField(default=0)),
                ('status', models.BooleanField(default=True)),
                ('birth_date', models.DateTimeField(default=0)),
                ('current_wallet', models.FloatField(default=0)),
                ('registration_wallet', models.FloatField(default=0)),
                ('sponsor_wallet', models.FloatField(default=0)),
                ('founder_wallet', models.FloatField(default=0)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(default=0)),
                ('agent_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agent.agent')),
                ('package_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_profile.package')),
                ('user_position_status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_profile.usepositionstatus')),
            ],
        ),
    ]
