# Generated by Django 3.1.5 on 2021-01-16 17:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('agent', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('package_name', models.CharField(default='primary', max_length=200)),
                ('package_amount', models.FloatField(default=0)),
                ('duration', models.TimeField(default=0)),
                ('description', models.TextField(blank=True, max_length=300, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UsePositionStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('status_id', models.CharField(max_length=250, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(blank=True, max_length=200, null=True)),
                ('address', models.TextField(blank=True, max_length=300, null=True)),
                ('country', models.CharField(blank=True, max_length=200, null=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='photos/%Y/%m/%d')),
                ('mobile_no', models.CharField(blank=True, max_length=20, null=True)),
                ('tnx_no', models.CharField(blank=True, editable=False, max_length=10, null=True)),
                ('sponsor_id', models.TextField(blank=True, max_length=200, null=True)),
                ('status', models.BooleanField(default=True)),
                ('birth_date', models.DateTimeField(blank=True, null=True)),
                ('current_wallet', models.FloatField(default=0)),
                ('registration_wallet', models.FloatField(default=0)),
                ('sponsor_wallet', models.FloatField(default=0)),
                ('founder_wallet', models.FloatField(default=0)),
                ('user_current_status', models.CharField(choices=[('NEW_USER', 'new'), ('ON_HOLD', 'hold'), ('TOP_HUNDRED', 'tophundred'), ('WINNER', 'winner')], default='new', max_length=11)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(blank=True, null=True)),
                ('agent_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='agent.agent')),
                ('package_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_profile.package')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('user_position_status', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user_profile.usepositionstatus')),
            ],
        ),
    ]
