# Generated by Django 3.1.5 on 2021-01-06 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='tnx_no',
            field=models.CharField(default='1004575582', editable=False, max_length=10, unique=True),
        ),
    ]
