# Generated by Django 3.1.5 on 2021-01-06 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0007_auto_20210106_0920'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='tnx_no',
            field=models.CharField(default='2608506843', editable=False, max_length=10, unique=True),
        ),
    ]
