# Generated by Django 3.1.5 on 2021-01-06 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0008_auto_20210106_1341'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='tnx_no',
            field=models.CharField(blank=True, editable=False, max_length=10, null=True),
        ),
    ]
