# Generated by Django 3.1.5 on 2021-01-06 18:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0004_auto_20210106_1803'),
        ('user_profile', '0009_auto_20210106_1825'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='agent_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='agent.agent'),
        ),
    ]
