# Generated by Django 3.1.5 on 2021-01-15 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0010_auto_20210106_1832'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='sponsor_id',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
    ]
